# frozen_string_literal: true

# Every auth flow terminates in the same JSON shape:
#   { access_token, refresh_token, expires_at, user }
# — generated by `render_auth(user)` below.
#
# Mobile login paths:
#   POST /api/v1/auth/sign_in   — email + password
#   POST /api/v1/auth/sign_up   — email registration
#   POST /api/v1/auth/google    — Google ID token verification
#   POST /api/v1/auth/apple     — Apple ID token verification
#   POST /api/v1/auth/facebook  — Facebook access token verification
#   POST /api/v1/auth/refresh   — exchange refresh_token → new access_token
#   GET  /api/v1/auth/me        — current user
#   DELETE /api/v1/auth/sign_out — client-side discard; 200 for symmetry
class Api::V1::AuthController < Api::V1::BaseController
  skip_before_action :authenticate_api_user!, only: %i[sign_in sign_up google apple facebook refresh]

  # ── Email / password ────────────────────────────────────────────────
  def sign_in
    user = User.find_by(email: params[:email]&.downcase&.strip)
    unless user&.valid_password?(params[:password])
      return render_error("Invalid email or password", :unauthorized)
    end
    render_auth(user)
  end

  def sign_up
    user = User.new(sign_up_params.merge(provider: "email"))
    if user.save
      render_auth(user, status: :created)
    else
      render_error(user.errors.full_messages.join(", "), :unprocessable_entity)
    end
  end

  # ── Social (server-side provider-token verification) ─────────────────
  def google
    verify_and_sign_in!(Auth::GoogleVerifier, params[:id_token])
  end

  def apple
    verify_and_sign_in!(Auth::AppleVerifier, params[:id_token])
  end

  def facebook
    claims = Auth::FacebookVerifier.call(params[:access_token])
    user   = Auth::SocialSignIn.call(claims)
    render_auth(user)
  rescue Auth::FacebookVerifier::VerificationError, Auth::SocialSignIn::Error => e
    render_error(e.message, :unauthorized)
  end

  # ── Token refresh ────────────────────────────────────────────────────
  def refresh
    payload = Auth::JwtIssuer.decode!(params[:refresh_token].to_s)
    return render_error("not a refresh token", :unauthorized) unless payload["type"] == "refresh"

    user = User.find(payload["user_id"])
    render_success(
      access_token: Auth::JwtIssuer.access_token(user),
      expires_at:   Auth::JwtIssuer::ACCESS_TTL.from_now
    )
  rescue JWT::DecodeError, ActiveRecord::RecordNotFound
    render_error("invalid refresh token", :unauthorized)
  end

  # ── Session introspection ────────────────────────────────────────────
  def me
    render_success(user: user_json(current_user))
  end

  def sign_out
    # JWT is stateless. Symmetry-only endpoint.
    render_success(message: "signed out")
  end

  private

  def sign_up_params
    params.permit(:email, :password, :password_confirmation, :first_name, :last_name)
  end

  def verify_and_sign_in!(verifier, token)
    claims = verifier.call(token.to_s)
    user   = Auth::SocialSignIn.call(claims)
    render_auth(user)
  rescue Auth::JwksVerifier::VerificationError, Auth::SocialSignIn::Error,
         KeyError, ActiveRecord::RecordInvalid => e
    render_error(e.message, :unauthorized)
  end

  def render_auth(user, status: :ok)
    render json: {
      access_token:  Auth::JwtIssuer.access_token(user),
      refresh_token: Auth::JwtIssuer.refresh_token(user),
      expires_at:    Auth::JwtIssuer::ACCESS_TTL.from_now,
      user:          user_json(user)
    }, status: status
  end

  def user_json(user)
    {
      id: user.id,
      email: user.email,
      first_name: user.first_name,
      last_name:  user.last_name,
      country:    user.country,
      timezone:   user.timezone,
      formality_level: user.formality_level,
      onboarded:  user.onboarded?,
      provider:   user.provider,
      roles:      user.roles.pluck(:name),
      knowledge_level: user.avatar&.knowledge_level || 1,
      created_at: user.created_at,
      updated_at: user.updated_at
    }
  end
end
