# Shrine uploader for chat-message audio.
#
# Two surfaces use this attachment:
#   1. User voice messages — m4a/aac uploaded by Expo's recorder.
#   2. Assistant TTS replies — mp3 generated by FastAPI /internal/audio/synthesize.
#
# Files are private (auth-gated download via MessageAudiosController#show).
# 25MB cap matches AudioChunkUploader so the mobile recorder constants stay
# unified; assistant TTS is well under 1MB in practice.
class MessageAudioUploader < Shrine
  storages[:store] = Shrine.storages[:store_private]

  plugin :determine_mime_type
  plugin :validation_helpers

  ALLOWED_MIME_TYPES = %w[
    audio/mp4
    audio/m4a
    audio/x-m4a
    audio/aac
    audio/mpeg
    audio/wav
    audio/x-wav
    audio/3gpp
    audio/ogg
    audio/flac
    video/mp4
    video/3gpp
  ].freeze

  AUDIO_EXTENSIONS = %w[.m4a .mp4 .aac .mp3 .wav .ogg .flac .3gp .3gpp].freeze

  Attacher.validate do
    validate_max_size 25.megabytes, message: "max 25MB per message"

    mime = file.mime_type
    filename = file.original_filename.to_s.downcase

    accepted =
      ALLOWED_MIME_TYPES.include?(mime) ||
      (mime == "application/octet-stream" &&
        AUDIO_EXTENSIONS.any? { |ext| filename.end_with?(ext) })

    unless accepted
      Shrine.logger.warn(
        "MessageAudioUploader: rejected mime=#{mime.inspect} filename=#{filename.inspect}"
      )
      errors << "audio file format not supported (detected #{mime.inspect})"
    end
  end
end
